import { useCallback, useState } from "react";
import { useBigPictureControls } from "../hooks/useBigPictureControls";
import { useUiSounds } from "../hooks/useUiSounds";

type AppInfo = Awaited<ReturnType<typeof window.gameVault.getAppInfo>>;
type LibraryPageProps = { appInfo: AppInfo | null; isBigPicture: boolean; library: LibraryState; onBigPictureChange: (enabled: boolean) => Promise<void>; onLibraryUpdated: (library: LibraryState) => void };
const navigation = ["Home", "Library", "Collections", "Settings"];

export function LibraryPage({ appInfo, isBigPicture, library, onBigPictureChange, onLibraryUpdated }: LibraryPageProps) {
  const [isImporting, setIsImporting] = useState(false);
  const [isCreatingCollection, setIsCreatingCollection] = useState(false);
  const [collectionName, setCollectionName] = useState("");
  const [query, setQuery] = useState("");
  const [favoritesOnly, setFavoritesOnly] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const sounds = useUiSounds();
  const exitBigPicture = useCallback(() => { void onBigPictureChange(false); }, [onBigPictureChange]);
  useBigPictureControls(isBigPicture, exitBigPicture);
  const normalizedQuery = query.trim().toLocaleLowerCase();
  const games = library.games.filter((game) => (!favoritesOnly || game.isFavorite) && (!normalizedQuery || game.title.toLocaleLowerCase().includes(normalizedQuery)));
  const focusProps = isBigPicture ? { "data-big-picture-focusable": "true" as const, onFocus: sounds.playFocus } : {};

  async function refreshLibrary() { onLibraryUpdated(await window.gameVault.getLibraryState()); }
  async function handleChooseFolder() { setIsImporting(true); setMessage(null); try { const result = await window.gameVault.chooseAndImportGames(); if (!result.canceled) { await refreshLibrary(); setMessage(result.imported ? `${result.imported} game${result.imported === 1 ? "" : "s"} imported.` : "No playable apps or executables were found."); sounds.playConfirm(); } } catch { setMessage("The folder could not be scanned. Please try another location."); } finally { setIsImporting(false); } }
  async function handleFavorite(game: Game) { await window.gameVault.setGameFavorite(game.id, !game.isFavorite); await refreshLibrary(); sounds.playConfirm(); }
  async function handleCreateCollection(event: React.FormEvent) { event.preventDefault(); const name = collectionName.trim(); if (!name) return; setIsCreatingCollection(true); setMessage(null); try { await window.gameVault.createCollection(name); setCollectionName(""); await refreshLibrary(); sounds.playConfirm(); } catch { setMessage("Collection names must be unique and between 1 and 60 characters."); } finally { setIsCreatingCollection(false); } }

  return <main className={`min-h-screen bg-zinc-950 text-zinc-100 ${isBigPicture ? "bg-[radial-gradient(circle_at_top,#27311f,#09090b_55%)]" : ""}`}><div className={`mx-auto grid min-h-screen max-w-[1600px] ${isBigPicture ? "grid-cols-[300px_1fr]" : "grid-cols-[240px_1fr]"}`}>
    <aside className={`border-r border-white/10 bg-zinc-900/40 px-5 py-7 ${isBigPicture ? "px-8 py-10" : ""}`}><div className="mb-12 flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-lime-400 font-black text-zinc-950">G</div><div><p className="font-semibold tracking-tight">GameVault</p><p className="text-xs text-zinc-500">Your games. One vault.</p></div></div>
      <nav aria-label="Primary navigation" className="space-y-2">{navigation.map((item) => <button {...focusProps} className={`w-full rounded-xl px-4 py-3 text-left text-sm transition focus:outline-2 focus:outline-offset-2 focus:outline-lime-400 ${item === "Library" ? "bg-white/10 font-medium text-white" : "text-zinc-400 hover:bg-white/5 hover:text-white"}`} key={item} type="button">{item}</button>)}</nav>
      <div className="mt-10"><p className="px-3 text-xs font-medium uppercase tracking-wider text-zinc-600">Collections</p><form className="mt-3 flex gap-2" onSubmit={handleCreateCollection}><input {...focusProps} aria-label="New collection name" className="min-w-0 rounded-lg border border-white/10 bg-zinc-950 px-2 py-1.5 text-xs outline-none placeholder:text-zinc-600 focus:border-lime-400" onChange={(event) => setCollectionName(event.target.value)} placeholder="New collection" value={collectionName} /><button {...focusProps} className="rounded-lg bg-white/10 px-2 text-sm hover:bg-white/15 disabled:opacity-50" disabled={isCreatingCollection} type="submit">+</button></form><ul className="mt-3 space-y-1">{library.collections.map((collection) => <li className="flex justify-between rounded-lg px-3 py-1.5 text-sm text-zinc-400" key={collection.id}><span className="truncate">{collection.name}</span><span className="text-xs text-zinc-600">{collection.gameCount}</span></li>)}</ul></div>
    </aside>
    <section className={`px-8 py-10 sm:px-12 ${isBigPicture ? "px-14 py-14" : ""}`}><header className="flex items-center justify-between gap-6"><div><p className="text-sm font-medium text-lime-400">GAMEVAULT {isBigPicture ? "BIG PICTURE" : "0.4"}</p><h1 className={`mt-2 font-bold tracking-tight ${isBigPicture ? "text-6xl" : "text-4xl"}`}>Your library.</h1></div><div className="flex items-center gap-3"><button {...focusProps} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm hover:bg-white/5 focus:outline-2 focus:outline-lime-400" onClick={() => void onBigPictureChange(!isBigPicture)} type="button">{isBigPicture ? "Exit Big Picture" : "Big Picture"}</button><div className="rounded-full border border-white/10 px-3 py-1.5 text-xs text-zinc-400">{appInfo?.databaseReady ? "Vault ready" : "Preparing vault…"}</div></div></header>
      <section className="mt-10 flex flex-wrap items-center gap-3"><input {...focusProps} aria-label="Search games" className="min-w-56 flex-1 rounded-xl border border-white/10 bg-zinc-900 px-4 py-3 text-sm outline-none placeholder:text-zinc-600 focus:border-lime-400" onChange={(event) => setQuery(event.target.value)} placeholder="Search your library" value={query} /><button {...focusProps} aria-pressed={favoritesOnly} className={`rounded-xl px-4 py-3 text-sm focus:outline-2 focus:outline-lime-400 ${favoritesOnly ? "bg-lime-400 font-medium text-zinc-950" : "border border-white/10 text-zinc-300 hover:bg-white/5"}`} onClick={() => setFavoritesOnly((current) => !current)} type="button">Favorites</button><button {...focusProps} className="rounded-xl bg-lime-400 px-4 py-3 text-sm font-semibold text-zinc-950 hover:bg-lime-300 focus:outline-2 focus:outline-lime-100 disabled:cursor-wait disabled:opacity-60" disabled={isImporting} onClick={handleChooseFolder} type="button">{isImporting ? "Scanning…" : "Add folder"}</button></section>
      {isBigPicture ? <p className="mt-4 text-xs text-zinc-500">D-pad or arrow keys to move · A / Enter to select · B / Escape to exit</p> : null}{message ? <p aria-live="polite" className="mt-4 text-sm text-lime-300">{message}</p> : null}
      <section className="mt-10"><div className="flex items-end justify-between"><div><p className="text-sm text-zinc-500">Library status</p><h2 className="mt-1 text-2xl font-semibold">{games.length} game{games.length === 1 ? "" : "s"} shown</h2></div><p className="text-xs text-zinc-600">{appInfo ? `Desktop engine connected · v${appInfo.version}` : "Connecting…"}</p></div>{games.length === 0 ? <p className="mt-6 rounded-2xl border border-dashed border-white/15 px-6 py-10 text-sm text-zinc-500">{library.games.length ? "No games match this filter." : "Add a folder to start building your library."}</p> : <ul className={`mt-6 grid gap-4 ${isBigPicture ? "sm:grid-cols-2 xl:grid-cols-4" : "sm:grid-cols-2 xl:grid-cols-3"}`}>{games.map((game) => <li key={game.id}><button {...focusProps} className={`w-full rounded-2xl border border-white/10 bg-white/[0.03] p-5 text-left transition hover:bg-white/[0.07] focus:scale-[1.03] focus:border-lime-400 focus:outline-2 focus:outline-lime-400 ${isBigPicture ? "min-h-44" : ""}`} onClick={() => void handleFavorite(game)} type="button"><div className="flex items-start justify-between gap-3"><p className="font-medium">{game.title}</p><span className={game.isFavorite ? "text-lime-400" : "text-zinc-600"}>★</span></div><p className="mt-2 truncate text-xs text-zinc-500" title={game.executablePath}>{game.executablePath}</p></button></li>)}</ul>}</section>
    </section>
  </div></main>;
}
